spring:
  application:
    name: transaksi

  profiles:
    active: local   # default kalau jalan dari IDE

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com